server:
  port: 8888
spring:
  application:
    name: cloud-gateway-eureka
  redis:
    host: localhost
    port: 6379
    database: 0
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
#AddRequestParameter 请求参数配置
#        - id: add_request_parameter_route
#          # 单服务
#          #uri: http://localhost:8001
#          #格式为：lb://应用注册服务名,实现负载
#          uri: lb://HELLO-SERVICE
#          filters:
#            - AddRequestParameter=foo, bar
#          predicates:
#            - Method=GET

#StripPrefix Filter 修改请求路径的过滤器
#         - id: nameRoot
#           uri: lb://HELLO-SERVICE
#           predicates:
#             - Path=/name/**
#           filters:
#             - StripPrefix=2
#        - id: nameRoot
#            uri: lb://HELLO-SERVICE
#            filters:
#              - PrefixPath=/mypath

# PrefixPath Filter 增加请求前缀
#        - id: prefixpath_route
#          uri: lb://HELLO-SERVICE
#          predicates:
#            - Method=GET
#          filters:
#            - PrefixPath=/mypath
#RequestRateLimiter TODO 限速路由器
#        - id: requestratelimiter_route
#          uri: lb://HELLO-SERVICE
#          filters:
#            #filter 名称必须是 RequestRateLimiter
#            - name: RequestRateLimiter
#              args:
#                #允许用户每秒处理多少个请求
#                redis-rate-limiter.replenishRate: 10
#                #令牌桶的容量，允许在一秒钟内完成的最大请求数
#                redis-rate-limiter.burstCapacity: 20
#                #使用 SpEL 按名称引用 bean
#                key-resolver: "#{@hostAddrKeyResolver}"
#          predicates:
#            - Method=GET
eureka:
  client:
    service-url:
      defaultZone: http://peer1:1111/eureka,http://peer2:1112/eureka
logging:
  level:
    org.springframework.cloud.gateway: debug