spring:
  application:
    name: hello-service

server:
  port: 8080

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://peer1:1111/eureka,http://peer2:1112/eureka
