server:
  port: 1111

eureka:
  instance:
    hostname: peer1
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://peer2:1112/eureka